### ISSUE TITLE
class temporary folder error on "make"

### ISSUE THREAD

**Issue by mariacara2** [joezuntz/cosmosis#104]
I am trying to install CosmoSIS on a cluster computer following the instructions outlined [here](https://cosmosis.readthedocs.io/en/latest/intro/installation.html#installing-manually-on-clusters-and-supercomputers). When I get to the "make" step, I receive the following error:

    ERROR: Command errored out with exit status 1:
     command: venv-directory/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-wrnr0iwm/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-wrnr0iwm/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-w1x9c6v9
         cwd: /tmp/pip-req-build-wrnr0iwm/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-wrnr0iwm/setup.py", line 34, in <module>
        with open(os.path.join(include_folder, 'common.h'), 'r') as v_file:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-wrnr0iwm/../include/common.h'
    ----------------------------------------

Does anyone know what this means and how I can fix it?

Thank you!

**Comment by joezuntz** [comment]
Hi there - sorry to miss this issue back when you made it. I guess it's "stale" now, but if not please re-open.
