### ISSUE TITLE
List sampler thinning and burn does nothing

### ISSUE THREAD

**Issue by itrharrison** [joezuntz/cosmosis#122]
Through lived experience and through inspecting the [code for the list sampler](https://github.com/joezuntz/cosmosis/blob/main/cosmosis/samplers/list/list_sampler.py) the `burn` and `thin` options do not currently function.

They could be made to function or simply removed. I'd prefer them to function as being able to generate some results on a short timescale (it currently only outputs once at the end of the run) is useful.

**Comment by joezuntz** [comment]
Fixed in version 3.7
