### ISSUE TITLE
Changing values/prior files in campaign

### ISSUE THREAD

**Issue by tilmantroester** [joezuntz/cosmosis#140]
Is it possible to specify different values and priors files in a campaign? Setting `pipeline.values` in `params` to a different file gets accepted without an error (as of 3.5.1) but the run then silently takes the original files from the base file.

**Comment by joezuntz** [comment]
This isn't supported. You'd need to use a different `base` choice. 

I will add an error if you try to do this, because it's not clear in what order everything should happen - if you inherit from a run which changes other parameters then which should take precedence?
