### ISSUE TITLE
Importance sampler column labels when running on a chain with log_weight column

### ISSUE THREAD

**Issue by jessmuir** [joezuntz/cosmosis#146]
Just flagging something that could be unexpected behavior: I've recently run an importance sampler, using an input chain that was run with nautilus. One way the nautilus chains differ from things run with other samplers I've worked with, is that it has a `log_weight` column instead of just `weight`. 

Usually when running the importance sampler on a nested sampler chain results in an output file which has one column called `old_weight` (the weight from the original chain), and one called `weight`, for the importance sampling weight from the ratio of the two posteriors in question. 

For the run on this nautilus chain, the last handful of column labels are `log_weight      prio
r       old_post        log_weight      post`. That is to say, there is no `old_weight`, there is just two copies of `log_weight`. It looks like the data in the columns are probably what they're supposed to be, so I think this is just an issue with the labels.

**Comment by joezuntz** [comment]
With apologies for the delay, I've opened PR #150  which I think addresses this. Do you have a simple test case lying around that should work for it?

**Comment by joezuntz** [comment]
This is now in the main branch.
