### ISSUE TITLE
ACT likelihood is causing random crashes 

### ISSUE THREAD

**Issue by ajshajib** [joezuntz/cosmosis#159]
First, thanks a lot to @joezuntz and all the other developers and contributors. The ease of use of this package to combine different datasets is truly amazing! 🤯🙏

When fitting the ΛCDM cosmology to DESI+CMB datasets, I am running into a mysterious crash when the ACT likelihood is included. The chain runs for a few hundred steps and then abruptly crashes with this error message:
```
...
Using likelihooods from first run:
 - act_dr6_lens
 - desi_bao
 - planck
Done 40 iterations of emcee. Acceptance fraction 0.435
Done 80 iterations of emcee. Acceptance fraction 0.378
Done 120 iterations of emcee. Acceptance fraction 0.355
Done 160 iterations of emcee. Acceptance fraction 0.349
Done 200 iterations of emcee. Acceptance fraction 0.342
Done 240 iterations of emcee. Acceptance fraction 0.341
Done 280 iterations of emcee. Acceptance fraction 0.343
Done 320 iterations of emcee. Acceptance fraction 0.342
Done 360 iterations of emcee. Acceptance fraction 0.342
Done 400 iterations of emcee. Acceptance fraction 0.343
Done 440 iterations of emcee. Acceptance fraction 0.343
Done 480 iterations of emcee. Acceptance fraction 0.344
Done 520 iterations of emcee. Acceptance fraction 0.344
Done 560 iterations of emcee. Acceptance fraction 0.344
Done 600 iterations of emcee. Acceptance fraction 0.344

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 1296364 RUNNING AT midway3-0154
=   EXIT CODE: 9
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Killed (signal 9)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions
```
If I don't include the ACT likelihood, then just the Planck+DESI run finishes successfully. I wonder if this is a known issue or if I am doing something wrong in my .ini file. Here's the .ini file; I would highly appreciate any suggestion to resolve the issue.
```
[runtime]
sampler = emcee
root = ${PWD}
verbosity = quiet

[pipeline]
modules = consistency camb planck act_dr6_lens sample_rdh desi
values = inis_lcdm/desi_planck_values.ini
extra_output =
debug=F
timing=F

[output]
filename = output/desi_planck_act_lcdm.txt
format = text

[emcee]
walkers = 192
samples = 4000
nsteps = 40

[act_dr6_lens]
file = ./likelihood/act-dr6-lens/act_dr6_lenslike_interface.py
like_corrections = T
variant = act_baseline ; actplanck_baseline

[planck]
file = likelihood/planck_py/planck_py_interface.py
use_low_ell_bins = T
spectra = TTTEEE
year = 2018

[camb]
nz_background = 300
zmin_background = 0.0
zmax_background = 3.0

file = boltzmann/camb/camb_interface.py
mode = cmb
lmax = 4000          ;max ell to use for cmb calculation
lens_margin = 1250
lens_potential_accuracy = 4
feedback=0         ;amount of output to print
AccuracyBoost=1.0 ;CAMB accuracy boost parameter
lSampleBoost = 1.0
lAccuracyBoost = 1.0
do_tensors = T   ;include tensor modes
do_lensing = T    ;lensing is required w/ Planck data
NonLinear = lens
theta_H0_range = "20 100"
halofit_version = takahashi

[sample_rdh]
file = utility/rescale_distances_rdh/rescale_distances_rdh.py

[desi]
file = likelihood/bao/desi1-dr1/desi1_dr1.py
desi_data_sets = BGS,LRG1,LRG2,LRG3+ELG1,ELG2,QSO,Lya QSO

[consistency]
file = utility/consistency/consistency_interface.py
```

**Comment by ajshajib** [comment]
Thanks a lot for the pointers, @joezuntz! I am pretty sure the crash was not due to reaching the time limit.  However, I will explore your suggestions and let you know of any updates.

**Comment by ajshajib** [comment]
I ran with the suggested changes, and it crashed again. I couldn't find anything eye-catching in the debug outputs. After some more digging around, I managed to get this info from the midway system:

```
       JobID    JobName      State    Elapsed 
------------ ---------- ---------- ---------- 
26862537       cosmosis OUT_OF_ME+   04:18:13 
```

So, indeed, it looks like a memory issue. This last run was with 96 MPI cores for 96 `emcee` walkers. I have run much longer `cosmosis+emcee` chains with higher number (200+) cores with the SN dataset, so just the walker/core number should not be a problem. Could it be that `nsteps = 40` is too large for the memory here? I allocate 2GB of RAM per core.

**Comment by joezuntz** [comment]
It's less likely to be nsteps than the overall number of tasks, and the tasks per core. I'm not super familiar with midway, but you could try cutting down to half the number of cores, or splitting them over more nodes.

**Comment by ajshajib** [comment]
I have rerun the job with 48 cores (for 48 walkers) from a single node, and it still crashes. However, it now crashes after roughly double the number of MCMC steps (the previous MCMC run used 96 walkers and 96 cores). So, my hunch is that there is a memory leak somewhere in the ACT likelihood computation.

Here's my values file, if you can kindly test on your end:

```
[cosmological_parameters]
; varied parameters for this run
h0 = 0.5 0.7 0.9
omega_m = 0.01 0.3 0.99
rdh = 10.0 100.0 1000.0
w = -1.0

; fixed parameters for this run
ombh2 = 0.02236
omega_k  =  0.0

;neutrinos
mnu = 0.06
nnu = 3.046
num_massive_neutrinos = 1


;helium 
yhe = 0.245341  ;helium mass fraction

;reionization
tau = 0.0697186      ;reionization optical depth

;inflation Parameters
n_s = 0.97      ;scalar spectral index
A_s = 2.19e-9    ;scalar spectrum primordial amplitude
k_s = 0.05      ;Power spectrum pivot scale 
n_run = 0.0     ;running of scalar spectrum 
r_t = 0.0       ;tensor to scalar ratio
n_t = 0.0       ;tensor spectral index 
```

**Comment by ajshajib** [comment]
I have found a solution to my issue. I was previously assigning 2GB of RAM to each core, as it was the maximum allowed amount in the previous HPC I was using. But, midway3 has up to 3.75GB available per core. So, I set the memory allocation to the maximum with `mem=0` in the sbatch file. And now the `emcee` chains are running until completion.

**Comment by joezuntz** [comment]
Great! Glad this worked out for you.  If you have more issues, the flag `--mem 60` for example would print out the memory usage every 60 seconds. This can sometimes be useful.
