### ISSUE TITLE
Missing "fastpt" module when trying to run project_2d

### ISSUE THREAD

**Issue by annmapo** [joezuntz/cosmosis#20]
The `fast-pt` python module seems to be missing in the default conda environment, which gives an error when trying to run `project_2d`. The issue is solved by installing the fast-pt module in the conda environment.

**Comment by joezuntz** [comment]
Hi Anna - is this on NERSC or a local conda install?

If it's NERSC then I've just fixed that.  If it's on your local machine then something's gone wrong, as it's supposed to be there.  Can you tell me the kind of machine you are on, and the output of the install process described here: https://cosmosis.readthedocs.io/en/latest/intro/installation.html#conda-forge-from-scratch

Thanks for spotting!

**Comment by annmapo** [comment]
Hi Joe,

It was on NERSC — I haven't tried yet on a local machine. Thanks for fixing that!
