### ISSUE TITLE
liblimber.so not found

### ISSUE THREAD

**Issue by amoradinejad** [joezuntz/cosmosis#22]
Hi Joe, 

Following the instructions you gave in #15 , I managed to successfully install my modified version of cosmosis (without conda) on a Linux cluster. However, when trying to run the code,  I get an error message that `OSError: liblimber.so: cannot open shared object file: No such file or directory`.  Checking the limber directory, the `liblimber.so` file is generated, so I dont understand the origin of the error. To give you a context, in my added modules, I am linking to liblimber to access the 2d interpolation functions (as described in [limber](https://bitbucket.org/joezuntz/cosmosis/wiki/liblimber)). Strangely enough on my laptop (MacOs), the code runs fine. I also didnt have any issue running the old version on the cluster. So I am quite puzzled by what is going on. 

Is there anything additional needed on the cluster to use the limber module in the new version of cosmosis?

Thanks.

**Comment by amoradinejad** [comment]
a quick update, when I change the Makefile of limber to the one in the old version of cosmosis, which builds static liblimber.a library, and link my code to it, and everything works fine. I couldn't figure out, though, what's the issue with the shared library. So if you had any insight on this, it would be great.

**Comment by joezuntz** [comment]
For your cluster, a short term fix is probably to do something like this:
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/cosmosis-standard-library/shear/limber
```
with /path/to/ replace with the absolute path to your installation, before running.

For a full solution you should probably add `-Wl,-rpath,$(PWD)/relative/path/to/limber/dir` to the Makefile for your new code where it makes the final library, where the relative path might be e.g. `../../shear/limber/` or something like that, depending where your code is in relation to the limber dir.

**Comment by amoradinejad** [comment]
@joezuntz  thanks a lot. I added the path to the Makefile of my code. You can close this issue.

**Comment by joezuntz** [comment]
Great!
