### ISSUE TITLE
Demo after installatiom

### ISSUE THREAD

**Issue by Lanzzyml** [joezuntz/cosmosis#27]
Hello , i just successfully installing cosmosis on my intel mac, i tried running the demo 1 , i keep getting this error: OSError: unable to open configuration file ‘demos/demo1.ini’

**Comment by joezuntz** [comment]
This sounds like you might be in the wrong directory. Did you run all the commands, including the one to download and and build `cosmosis-standard-library`? If so, could you tell me which method you used to install (conda, pip, etc?)

**Comment by Lanzzyml** [comment]
I used conda, when i access the cosmosis using jupyter notebook i see the standard-build library in which see directories like boltzmann, examples and demos. Also i tried to build the standard library again i got a message that the directory already exists and it’s not empty. Running cosmosis —help works

**Comment by joezuntz** [comment]
Are you running from a jupyter notebook using the `!` syntax, like this:
```
! cosmosis demos/demo1.ini
```
?

If so then you probably need to move the notebook to being inside the `cosmosis-standard-libary` directory.

**Comment by Lanzzyml** [comment]
Many thanks i just had to set directory to cd cosmosis-standard-build and it worked

**Comment by joezuntz** [comment]
Great, glad it worked! I'll close this now but you're welcome to re-open for other issues.
