### ISSUE TITLE
Problem Installing Cosmosis

### ISSUE THREAD

**Issue by Eminencetoosure** [joezuntz/cosmosis#30]
Hi Joe,

I am currently working on installing cosmosis on my machine, i was able to install it on my standard library and i cant check the version of the cosmosis (2.0.8) but moving forward trying to work on the demos, i was not able to run the demos esp "cosmosis examples/planck.ini" . 
i am getting "permission denied".  i don't know if I have done something wrong but I must say I have been following the installation procedure from the start. 
![20220619 053923 1](https://user-images.githubusercontent.com/12238297/174491375-3c9e4fe3-e9dc-4827-86bc-a7ad8b9a5658.jpeg)

**Comment by Eminencetoosure** [comment]
Thank you joe.

**Comment by joezuntz** [comment]
I'll close this issue for now but please do re-open if useful.
