### ISSUE TITLE
default halo model parameters for mead2020?

### ISSUE THREAD

**Issue by jessmuir** [joezuntz/cosmosis#39]
I'm working on setting up a test pipeline using HMcode2020 for the nonlinear matter power spectrum and want to make sure I understand the input parameters. 

Based on my reading of the pycamb code, for camb setting the nonlinear power spectrum to 'mead2020' specifies the dark matter only version of HM code, while mead2020_feedback specifies the version with baryonic feedback. It seems the baryonic feedback version needs three parameters A, eta, and logT, which have default values specified.

The cosmosis camb interface looks like it will require A and eta0 to be specified as part of halo_model_parameters in the values file whether or not `_feedback` is part of the nonlinear model name. Because of this, even when I just specify mead2020 I get errors for not having those parameters, even though (I think) they wouldn't be used. 

If I'm understanding this structure correctly, it might be preferrable to edit the camb_interface in cosmosis to only require those feedback parameters if the nonlinear model is specifically mead2020_feedback, or at least to set up default values matching the camb defaults so that they can be optional in cosmosis runs.

**Comment by jessmuir** [comment]
On a related note, I'm noticing that the CAMB interface only allows us to set two of the three HMcode baryonic feedback parameters. The missing parameter is set in CAMB via HMCode_logT_AGN; as things are we can only run with it set to the default value of 7.8.

**Comment by joezuntz** [comment]
@jessmuir thanks for spotting this!  Could you have a look at the change here and see if you think it makes sense:
https://github.com/joezuntz/cosmosis-standard-library/pull/26/files
?

**Comment by jessmuir** [comment]
The CAMB documentation (https://camb.readthedocs.io/en/latest/nonlinear.html)  doesn't say whether certain parameters can only be used with certain hmcode versions. and I'm not familiar enough with it to know e.g.  whether only T_AGN can be set for mead2020 or if all three parameters should be accessible. But as long as that's been checked, I think this makes sense!

**Comment by joezuntz** [comment]
I've just opened a PR on the main camb repo to update the docstrings, and at the same time check I've understood this!

**Comment by joezuntz** [comment]
Antony has merged them so presumably they are right!

**Comment by joezuntz** [comment]
[Fixed in cosmosis PR 26](https://github.com/joezuntz/cosmosis-standard-library/pull/26).
