### ISSUE TITLE
CAMB interface: accurate_massive_neutrinos argument name mismatch

### ISSUE THREAD

**Issue by jessmuir** [joezuntz/cosmosis#40]
I was attempting to set the optional camb setting of `accurate_massive_neutrinos` to T, but got the error 
```
TypeError: set_matter_power() got an unexpected keyword argument 'accurate_massive_neutrinos'
```

Looking through the camb code that this gets passed to, it looks like that function in `camb.py` takes an argument with a slightly different name `accurate_massive_neutrino_transfers`, and things seem to work if I change the name of the optional parameter in `the camb_interface.py` and ini files to match.

**Comment by joezuntz** [comment]
Thanks for spotting this! I'm testing a fix now in [this CSL PR](https://github.com/joezuntz/cosmosis-standard-library/pull/27),

**Comment by joezuntz** [comment]
Fix is merged in CSL.
