### ISSUE TITLE
Undefined symbol error with ACT DR4 likelihood

### ISSUE THREAD

**Issue by margaret-ikape** [joezuntz/cosmosis#47]
Hi @joezuntz ,

I have just installed the new cosmosis version and included the ACT likelihood (which runs fine), but when I try to run the test sampler on the ACT likelihood, I get 
```
File "/home/margaret/env/lib/python3.9/site-packages/cosmosis/runtime/module.py", line 103, in __init__
    self.library, language = self.load_library(filename)
  File "/home/margaret/env/lib/python3.9/site-packages/cosmosis/runtime/module.py", line 291, in load_library
    raise SetupError("You specified a path %s for a module. "
cosmosis.runtime.module.SetupError: You specified a path /home/margaret/cosmosis-standard-library/likelihood/actpolfull_dr4.01/actpol.so for a module. File exists, but could not be opened. Error was /home/margaret/cosmosis-standard-library/likelihood/actpolfull_dr4.01/actpol.so: undefined symbol: __cosmosis_modules_MOD_datablock_put_double
```
Could you please tell me what I'm doing wrong?

Thank you!

**Comment by joezuntz** [comment]
Hi @margaret-ikape ,

ACTPol isn't included with cosmosis, so I think this is a module you've installed separately?  

I can see the actpolfull_dr4.01 file is publicly available, but I'm not sure what interface file you're using (i.e. the file with the setup and execute functions), or the Makefile. If you're able to share those I can have a look.

In general, though, the error you're seeing happens when flags looking something like this are missing from a Makefile:

```
USER_FFLAGS+=-Wl,-rpath,${PWD}
USER_LDFLAGS+=-Wl,-rpath,${PWD} -lcosmosis
```

best,
Joe

**Comment by margaret-ikape** [comment]
Thanks, @joezuntz. I added the two lines above and it works fine now.

Thanks again,

**Comment by joezuntz** [comment]
Great, glad this worked for you! If you're able to share the likelihood code interface to cosmosis so I could package it with cosmosis then that would be really great (I have a vague memory of discussing this with Renee Hlozek at one point). No worries if not, or not yet.

I'll close this issue now.
Cheers,
Joe

**Comment by margaret-ikape** [comment]
Absolutely. I’m going to confirm the likelihood is installed properly by reproducing the results from the ACT paper, and then I can share it with so it can be added.

Thanks again,

Margaret

**Comment by margaret-ikape** [comment]
Hi Joe,

I hope this message meets you well. I’ve recently come back to the ACT likelihood and I’m running some checks to reproduce the results from https://arxiv.org/pdf/2007.07289.pdf <https://arxiv.org/pdf/2007.07289.pdf>. I’m finding that when I set NonLinear in the cosmosis ini file to ‘both’ or ‘lens’, I get the same result. Same goes for NonLinear = ’none’ and ‘pk’. I tried to look through the CAMB code in cosmosis and found the following code.
I think I found something in env/lib/python3.9/site-packages/camb/model.py . checking it out


Margaret Ikape
  2:52 PM <https://astro-uoft.slack.com/archives/D4N9WHQ3C/p1669751570902509>
in def  set_non_linear_lensing, we have
if nonlinear:
      if self.NonLinear in [NonLinear_pk, NonLinear_both]:
        self.NonLinear = NonLinear_both
      else:
        self.NonLinear = NonLinear_lens
    else:
      if self.NonLinear in [NonLinear_pk, NonLinear_both]:
        self.NonLinear = NonLinear_pk
      else:
        self.NonLinear = NonLinear_none
2:57 <https://astro-uoft.slack.com/archives/D4N9WHQ3C/p1669751828086479>
i guess this means that if nonlinear is True, that is NonLinear != none, and if the user chooses either pk or both, then code defaults to both, otherwise, code defaults to lens (This probably explains why NonLinear = both and lens give same result   (?)  )
otherwsie, if nonlinear is not true, then code defaults to either pk or none (which again explains why NonLinear = none and pk give same reult)





2:57 <https://astro-uoft.slack.com/archives/D4N9WHQ3C/p1669751847342459>
Is this correct? am i reading the cdoe correctl
I think I found something in env/lib/python3.9/site-packages/camb/model.py . checking it out


Margaret Ikape
  2:52 PM <https://astro-uoft.slack.com/archives/D4N9WHQ3C/p1669751570902509>
in def  set_non_linear_lensing, we have
if nonlinear:
      if self.NonLinear in [NonLinear_pk, NonLinear_both]:
        self.NonLinear = NonLinear_both
      else:
        self.NonLinear = NonLinear_lens
    else:
      if self.NonLinear in [NonLinear_pk, NonLinear_both]:
        self.NonLinear = NonLinear_pk
      else:
        self.NonLinear = NonLinear_none
2:57 <https://astro-uoft.slack.com/archives/D4N9WHQ3C/p1669751828086479>
i guess this means that if nonlinear is True, that is NonLinear != none, and if the user chooses either pk or both, then code defaults to both, otherwise, code defaults to lens (This probably explains why NonLinear = both and lens give same result   (?)  )
otherwsie, if nonlinear is not true, then code defaults to either pk or none (which again explains why NonLinear = none and pk give same reult)
2:57 <https://astro-uoft.slack.com/archives/D4N9WHQ3C/p1669751847342459>
Is this correct? am i reading the cdoe correctly?

In env/lib/python3.9/site-packages/camb/model.py 

In def  set_non_linear_lensing, 
if nonlinear:
      if self.NonLinear in [NonLinear_pk, NonLinear_both]:
        self.NonLinear = NonLinear_both
      else:
        self.NonLinear = NonLinear_lens
    else:
      if self.NonLinear in [NonLinear_pk, NonLinear_both]:
        self.NonLinear = NonLinear_pk
      else:
        self.NonLinear = NonLinear_none

I guess this means that if nonlinear is True, that is NonLinear != none, and if the user chooses either pk or both, then code defaults to both, otherwise, code defaults to lens (This probably explains why NonLinear = both and lens give same result   (?) )

otherwsie, if nonlinear is not true, then code defaults to either pk or none (which again explains why NonLinear = none and pk give same reult)

Is this correct? am I reading the code correctly?


Thanks,
Margaret

I think I found something in env/lib/python3.9/site-packages/camb/model.py . checking it out


Margaret Ikape
  2:52 PM <https://astro-uoft.slack.com/archives/D4N9WHQ3C/p1669751570902509>
in def  set_non_linear_lensing, we have
if nonlinear:
      if self.NonLinear in [NonLinear_pk, NonLinear_both]:
        self.NonLinear = NonLinear_both
      else:
        self.NonLinear = NonLinear_lens
    else:
      if self.NonLinear in [NonLinear_pk, NonLinear_both]:
        self.NonLinear = NonLinear_pk
      else:
        self.NonLinear = NonLinear_none
2:57 <https://astro-uoft.slack.com/archives/D4N9WHQ3C/p1669751828086479>
i guess this means that if nonlinear is True, that is NonLinear != none, and if the user chooses either pk or both, then code defaults to both, otherwise, code defaults to lens (This probably explains why NonLinear = both and lens give same result   (?)  )
otherwsie, if nonlinear is not true, then code defaults to either pk or none (which again explains why NonLinear = none and pk give same reult)
2:57 <https://astro-uoft.slack.com/archives/D4N9WHQ3C/p1669751847342459>
Is this correct? am i reading the cdoe correctly?
