### ISSUE TITLE
Cosmosis doesn't look for the right theory predictions

### ISSUE THREAD

**Issue by rpaviot** [joezuntz/cosmosis#48]
Hi,

I would like to use Cosmosis in order to fit projected measurements ( wg+/wgg)
I created a new theory block (tested with the test module), modified type_table.txt and twopoint.py to load the correct datasets from the .fits input.
I have defined in twopoint.py :
galaxy_position_red = "GPS"
galaxy_shear_plus_red = "G+S"
for redshift space quantities, which are passed to type_table as :
galaxy_position_red galaxy_shear_plus_red section_name theta bin_{0}_{1}

Then i call the module likelihood/2pt/2pt_like.py.
This module does give me the data and covariance measurements that i want.
But it doesn't not give the correct theory predictions. I have tried to give to the 2pt module the options
x_name, y_name, x_section,y_section (with x_section = y_section = section_name defined in type_table.txt) but it looks like Cosmosis doesn't use them at all. In order to perform the fit,
i had to change by hand the python function extract_theory_point from the gaussian_likelihood.py module.

Should i pass the options x_name, y_name, x_section,y_section to an other cosmosis module to make it work?
Thanks,

Romain

**Comment by joezuntz** [comment]
Something like what you're descrbing should work, as long as the 2pt data file that you're using contains the correct data. It's quite hard to diagnose this without seeing the code and data - are you able to share those? By email if you prefer not to make them public?

**Comment by rpaviot** [comment]
Many thanks for you fast answer.
You can see the code here :  https://github.com/rpaviot/echoIA-cosmosis/
In the cosmosis folder, there are changes done within the python files of cosmosis.
In the measure folder, there is a notebook which create the .fits file (but the error is not coming from here i guess, since cosmosis gets the measured wgp)
In the theory folder, you can see the .ini file, where the output of projected_alignments_interface.py goes into the "projected_galaxy_intrinsic"  section  (for wgp), which appears into the 2pt modules. If instead of using "extract_theory_points", i used the new defined function "extract_theory_points_wgp(/g)", the fit performs just fine (see the notebook in the theory folder.)

**Comment by joezuntz** [comment]
I don't see your new version of 2pt_like.py there - could you share that?

**Comment by rpaviot** [comment]
I haven't performed any change to 2pt_like.py as i thought it was only a sub-class of gaussian_likelihood.py.  extract_theory_points is defined in both 2pt_like.py and gaussian_likelihood.py

**Comment by joezuntz** [comment]
@rpaviot apologies that I never followed up here. Is there anything useful that we could look at now?

**Comment by rpaviot** [comment]
Hello,

No problem.
I tried to solve this issue but i couldn't, so i switched to fast-pt for
the theoritical predictions and implemented the sampler myself.

Cheers,
Romain
