### ISSUE TITLE
des-y3 with class

### ISSUE THREAD

**Issue by borisbolliet** [joezuntz/cosmosis#64]
Hi Joe,

I am trying to test des-y3 with class rather than camb. I am starting from your example ini file which uses camb. I am setting it up so it uses class but when I run the code I get errors due to the format of P(k)'s....

Do you have an example ini file that uses class fro des-y3?

Cheers,
Boris

**Comment by borisbolliet** [comment]
I managed to solve the P(k) errors by switching the order of the indices in fast_pt_interface.py:

    P0 = Pkz[0,:]  # camb
    P0 = Pkz[:,0] # class

    Growth2 = Pkz[:,ind]/Pkz[0,ind] # camb
    Growth2 = Pkz[ind,:]/Pkz[ind,0] # class

I also had to add:

    block[distances, 'a'] = 1/(1+z)

in class_interface.py

(Sorry I am realising I should have opened this issue in the osmosis-standard-library GitHub :/)

**Comment by joezuntz** [comment]
Hi @borisbolliet ,

Thanks for finding these issues! I am testing DES-Y3 with class now here:
https://github.com/joezuntz/cosmosis-standard-library/pull/50

There are some class/camb differences in massive neutrino handling which give a detectable difference in likelihood between the two. I don't quite understand neutrinos enough to know if this is physics or parameterization!

In general though this should be usable once the tests all pass and I merge.

Cheers!
Joe

**Comment by borisbolliet** [comment]
ah yes I forgot about the neutrinos setting, I did have to modify the interface where I hardcode, 1 massive neutrino:

    params = {
        'output': choose_outputs(config),
        'lensing':   'yes' if config['lensing'] else 'no',
        'A_s':       block[cosmo, 'A_s'],
        'n_s':       block[cosmo, 'n_s'],
        'H0':        100 * block[cosmo, 'h0'],
        'omega_b':   block[cosmo, 'ombh2'],
        'omega_cdm': block[cosmo, 'omch2'],
        'tau_reio':  block[cosmo, 'tau'],
        'T_cmb':     block.get_double(cosmo, 'TCMB', default=2.726),
        # 'N_ur':      nnu - nmassive,
        # 'N_ncdm':    nmassive,
        # 'm_ncdm':    block.get_double(cosmo, 'mnu', default=0.06)
      'N_ncdm': 1,
      'N_ur': 2.0328,
      'm_ncdm': 0.06
    }


Thank you so much!
