### ISSUE TITLE
Fisher Matrix Project

### ISSUE THREAD

**Issue by joezuntz** [joezuntz/cosmosis#68]
Following up with @Gabriel-Rodrigues1

> Is a clustering and weak lensing survey, its actually the JPAS. Since I am interested in the Impact that the massive neutrinos has especially in the growth of structure, I am looking to the Matter power spectrum. And for what I understand the code can provide the linear and non linear regime, its that correct?
> And also, can I choose the Fisher matrix parameters?

Yes - the camb module will generate linear and nonlinear matter power spectra. You have a few choices about which options to use, in the parameter file.  You could have a look at the LSST example for some starting points, and documentation on the readthedocs page.

You can choose which parameters to make the FM over by changing the values file. You can fix any parameters you don't want included.

Fisher matrices can sometimes be difficult with neutrino mass because the fiducial value is usually very close to the edge of the parameter space at zero. You could try, though you might need to switch to a different starting value.

**Comment by Gabriel-Rodrigues1** [comment]
Thank you very much. Your answers were very helpful. I'll take a look at the LSST example and try to get started.

**Comment by Gabriel-Rodrigues1** [comment]
Hi Joe,

I apologize for bothering you again, but I am really interested in using Cosmosis for my work and I have a few questions. Based on my understanding of the LSST example that you recommended, the survey forecast is conducted using the 2pt module. This module requires input of the survey specifics and will produce useful outputs. However, to use it, we need a .fits file with some simulated information such as the covmat, shear_cl, and nz_lens. Do I have to generate it for the Survey I am interested in? If so, is there a specific module I can use to do it?

Thank you in advance for your time and assistance.

**Comment by joezuntz** [comment]
Hi @Gabriel-Rodrigues1 

The only thing that you need to pre-generate is the n(z) choice, which will be specific to the survey you are implementing. You can make this into a text file and then switch out the two "smail" modules in the `lsst_simulate.ini` file for the for the [load_nz](https://cosmosis.readthedocs.io/en/latest/reference/standard_library/load_nz.html) module to read from file.

Then you can choose the other survey ans observation properties in the `save_simulation` section of `lsst_simulate`, re-run that part of the pipeline, and that should be the main thing you need to do. Happy to chat more if useful.

**Comment by Gabriel-Rodrigues1** [comment]
Thank you for your response. Just to confirm that I understand correctly, I will use the Smail module to obtain the n(z) data for the survey, and then I will use the load_nz module to load it instead of using the load_nz_fits, is that correct?

In the save_simulation section of lsst_simulate, it appears that we also need to define the .fits file in 'filename'. I believe this is necessary to generate the Gaussian Covmat. Also in the 2pt_like module from the lsst_analyze. Could you please confirm and clarify this for me?

**Comment by joezuntz** [comment]
Hi @Gabriel-Rodrigues1 - sorry I forgot to reply to this last time.  You could generate the n(z) using the smail module in one pipeline, then take the results after using the test sampler and put it together to use in the load_nz sampler.

Or you could just make up your own n(z) for whatever you are simulating and use that instead.

The filename in the lsst_simulate module is what it saves the file as. The filename in 2pt_like reads that same file after you have created it with the first pipeline.
