### ISSUE TITLE
Missing conda-forge builds for osx-arm64

### ISSUE THREAD

**Issue by tilmantroester** [joezuntz/cosmosis#7]
The builds on conda-forge don't seem to include osx-arm64: https://anaconda.org/conda-forge/cosmosis/files
Is that just a conda-forge issue, since the installation documentation mentions Apple silicon and it seems to build fine via `pip`?

**Comment by joezuntz** [comment]
Yes, this is just that I hadn't yet enabled this on Silicon. I'll attempt that now:
https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2675

**Comment by joezuntz** [comment]
This turns out not to be easy at this point, since you have to cross-compile.

**Comment by joezuntz** [comment]
This has been working for a while now, thanks to the conda-forge team.
