### ISSUE TITLE
Nautilus and blobs

### ISSUE THREAD

**Issue by johannesulf** [joezuntz/cosmosis#72]
Thanks so much for helping to implement nautilus. I tested it on some DES likelihoods and it works fine for the most part. There is one minor, non-urgent issue in the implementation. If only one blob is returned with the likelihood, i.e., only the prior, `nautilus.posterior(return_blobs=True)` will return a one-dimensional array for the blobs, not two-dimensional. This leads to a crash since cosmosis implicitly assumes the array to be two-dimensional.

**Comment by joezuntz** [comment]
Ah, thanks for spotting this!  I'll look at a fix now.
