### ISSUE TITLE
Error using polychord on nersc

### ISSUE THREAD

**Issue by andluizsouza** [joezuntz/cosmosis#8]
Hi everyone!

I am trying to run some cosmosis chains on NERSC using the polychord sampler, but I have faced this error message:

`/global/cfs/cdirs/des/zuntz/cosmosis-global/env-1/lib/python3.9/site-packages/cosmosis/samplers/polychord/polychord_src/libchord_mpi.so: cannot open shared object file: No such file or directory
PolyChord could not be loaded.`

In fact, there is no the `libchord_mpi.so` file in that directory, only `libchord.so`. 

Could anyone help me with this issue, please?

PS: I have used the command `source $CFS/des/zuntz/cosmosis-global/setup-cosmosis-nersc` to setup the env, according to the documentation: https://cosmosis.readthedocs.io/en/latest/intro/installation.html?highlight=nersc#nersc

**Comment by joezuntz** [comment]
Hi @andluizsouza 

It looks like there was some kind of mistake in my setup process, but I have re-run it and installed a new version centrally.

I've updated the setup script so you should now get the newest version automatically.  I have run the polychord and multinest samplers under MPI and both seems to work.

It's probably not needed, but running `make clean; make` for safety can't hurt.

Thanks for spotting this, and please do re-open if you seen any more problems with this.
