### ISSUE TITLE
Possible error in implementation of dynesty and nautilus

### ISSUE THREAD

**Issue by johannesulf** [joezuntz/cosmosis#80]
I believe both dynesty and nautilus may not be correctly implemented/interfaced. The problem is that dynesty seems to be passed the posterior function when it expects the likelihood function. I then modeled the implementation of nautilus into cosmosis after dynesty's, likely copying this mistake. Sorry for not catching that earlier.

**Comment by joezuntz** [comment]
Many thanks for spotting this! I have released a fixed version, 2.3.2.
