### ISSUE TITLE
Constant extrapolation of matter power spectrum at large scales

### ISSUE THREAD

**Issue by itutusaus** [joezuntz/cosmosis#9]
Hi, I have observed that extending the kmin value below 1e-4 when calling camb for the matter power spectrum leads to a constant extrapolation using  the value of the spectrum at k=1e-4. To reproduce the issue one option is to set kmin=1e-5 in examples/des-y3.ini instead of kmin=1e-4. I have tested a decrease of kmin with an external version of camb and the extrapolation seems to follow a power law. Might this constant extrapolation be coming from the camb_interface.py? 

Thanks in advance

**Comment by joezuntz** [comment]
I can replicate this exactly, but haven't been able to track it down. I'll keep looking but ideas welcome.

**Comment by joezuntz** [comment]
Tilman Troester has kindly dealt with this at last - we now simply use the camb min k value, which should never require extrapolation.
